"""empty message

Revision ID: 1d86609f42d2
Revises: None
Create Date: 2015-12-07 21:59:33.403756

"""

# revision identifiers, used by Alembic.
revision = '1d86609f42d2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('absolute_uid', sa.Integer(), nullable=False),
    sa.Column('classic_email', sa.String(), nullable=False),
    sa.Column('classic_mirror', sa.String(), nullable=False),
    sa.Column('classic_cookie', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('absolute_uid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
