"""empty message

Revision ID: c73c098fb8c5
Revises: 1d86609f42d2
Create Date: 2016-03-11 16:48:49.544750

"""

# revision identifiers, used by Alembic.
revision = 'c73c098fb8c5'
down_revision = '1d86609f42d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twopointoh_email', sa.String(), nullable=True))
    op.alter_column('users', 'classic_cookie',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'classic_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'classic_mirror',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'classic_mirror',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'classic_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'classic_cookie',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'twopointoh_email')
    ### end Alembic commands ###
